version: "3.8"
 
services:
 
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - catalog-service
      - recommendation-service
      - cart-service
      - payment-service
    networks:
      - red-app
 
  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      - mongodb
    networks:
      - red-app
 
  catalog-service:
    build: ./catalog-service
    container_name: catalog-service
    depends_on:
      - mongodb
    networks:
      - red-app
 
  recommendation-service:
    build: ./recommendation-service
    container_name: recommendation-service
    depends_on:
      - user-service
      - catalog-service
    networks:
      - red-app
 
  cart-service:
    build: ./cart-service
    container_name: cart-service
    depends_on:
      - mongodb
    networks:
      - red-app
 
  payment-service:
    build: ./payment-service
    container_name: payment-service
    depends_on:
      - mongodb
    networks:
      - red-app
 
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    networks:
      - red-app
 
  k6:
    image: grafana/k6
    container_name: k6-prueba
    volumes:
      - ./tests:/scripts
    depends_on:
      - api-gateway
    command: run /scripts/performance-test.js
    networks:
      - red-app
 
volumes:
  mongo_data:
 
networks:
  red-app: